config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "landing#home"

  resources :leads do
    member do
      post 'claim'
      post 'unclaim'
    end
  end

  get '/my_leads' => 'claims#index'
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  belongs_to :user

  validates :company_id, uniqueness: true, case_sensitive: false
  validates :company_id, numericality: { only_integer: true }

  validates :company_name, presence: true

  validates :phys_address, presence: true

  validates :phys_city, presence: true
  validates_format_of :phys_city, with: /[a-z]/

  validates :phys_state, presence: true

  validates :phys_zip, presence: true
  validates :phys_zip, numericality: { only_integer: true }
  validates :phys_zip, length: { is: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :leads

  validates :first_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
  end
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  def index
    @user = current_user
    @leads = Lead.where("user_id = ?", @user.id)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def home
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def index
    @user = current_user
    @leads = []

    if params[:q1].nil? == false
      if valid_search?
        @leads = search(*search_params)
      else
        flash[:error] = "At least one field must be filled!"
        render :index
      end
    end
  end

  def show
    @user = current_user
    @lead = Lead.find(params[:id])
  end

  def new
    @user = current_user
    @lead = Lead.new
  end

  def create
    @user = current_user
    @lead = Lead.new(lead_params)

    @lead.company_id = create_id

    if @lead.save
      flash[:notice] = "Your lead has been saved to the database."
      redirect_to lead_path(@lead)
    else
      flash[:errors] = @lead.errors.full_messages.join(". ")
      render :new
    end
  end

  def claim
    @lead = Lead.find(params[:id])
    @user = current_user
    current_lead = Lead.find(params[:id])
    current_lead.update_attribute(:status, current_lead.status = 1)
    current_lead.update_attribute(:user_id, current_lead.user_id = @user.id)
    redirect_to lead_path(@lead)
    flash[:notice] = "Lead claimed successfully."
  end

  def unclaim
    @lead = Lead.find(params[:id])
    current_lead = Lead.find(params[:id])
    current_lead.update_attribute(:status, current_lead.status = 0)
    current_lead.update_attribute(:user_id, current_lead.user_id = 0)
    redirect_to :back
    flash[:notice] = "Lead unclaimed successfully."
  end

  protected

  def lead_params
    params.require(:lead).permit(:company_name,
                                :phys_address,
                                :phys_city,
                                :phys_state,
                                :phys_zip,
                                :description,
                                :phone,
                                :alt_phone,
                                :toll_free_phone,
                                :fax_phone,
                                :website,
                                :email,
                                :mail_address,
                                :mail_city,
                                :mail_state,
                                :mail_zip,
                                :employees_on_site,
                                :annual_sales,
                                :year_est,
                                :area_of_dist,
                                :ownership,
                                :imports,
                                :woman_owned,
                                :minority_owned)
  end

  def valid_search?
    if params[:q1] == "" &&
        params[:q2] == "" &&
        params[:q3] == "" &&
        params[:q4] == "" &&
        params[:q5] == ""

      return false
    else
      return true
    end
  end

  def search_params
    [params[:q1], params[:q2], params[:q3], params[:q4], params[:q5]]
  end

  def create_id
    Time.now.strftime("%H%M%S")
  end

  def search(q1, q2, q3, q4, q5)
    vars = []
    query = ""

    if q1 != ""
      query += "LOWER(company_name) LIKE LOWER(?)"
      vars << '%' + q1 + '%'
    end

    if q2 != ""
      if query == ""
        query += "LOWER(phys_address) LIKE LOWER(?)"
      else
        query += " AND LOWER(phys_address) LIKE LOWER(?)"
      end
      vars << '%' + q2 + '%'
    end

    if q3 != ""
      if query == ""
        query += "LOWER(phys_city) LIKE LOWER(?)"
      else
        query += " AND LOWER(phys_city) LIKE LOWER(?)"
      end
      vars << '%' + q3 + '%'
    end

    if q4 != ""
      if query == ""
        query += "LOWER(phys_state) LIKE LOWER(?)"
      else
        query += " AND LOWER(phys_state) LIKE LOWER(?)"
      end
      vars << '%' + q4 + '%'
    end

    if q5 != ""
      if query == ""
        query += "LOWER(phys_zip) LIKE LOWER(?)"
      else
        query += " AND LOWER(phys_zip) LIKE LOWER(?)"
      end
      vars << '%' + q5 + '%'
    end
    Lead.where(query, *vars).order(company_name: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ownership_helper.rb
module OwnershipHelper
  def ownership
    [
      ['Select', nil],
      ['Sole Ownership', 'Sole Ownership'],
      ['Partnership', 'Partnership'],
      ['Public Corporation', 'Public Corporation'],
      ['Private Corporation', 'Private Corporation'],
      ['Limited Liability Company (LLC)', 'Limited Liability Company']
    ]
  end
end

app/helpers/states_helper.rb
module StatesHelper
  def us_states
    [
      ['Select', nil],
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY']
    ]
  end
end

app/views/claims/index.html.erb
<h2 id="claimed-leads-show-header">Your Claimed Leads:</h2>

<div class="row">
  <div class="medium-12 columns">
    <div class="boxed" id="claimed-leads-show-box">
      <div id="claimed-leads-show-list">
        <ul id="claimed-list">
          <% @leads.each do |lead| %>
          <li><a href="/leads/<%=lead.id%>"><%=lead.company_name%></a>  <%= link_to "Unclaim Lead", {:controller => "leads", action: "unclaim", id: lead.id}, method: :post, class: "button", style: "width:165px;height:50px;" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="back-to-search">
  <%= link_to "← Return to Search", leads_path %>
</div>

app/views/claims/show.html.erb
<h2 id="claimed-leads-show-header">Your Claimed Leads:</h2>

<div class="row">
  <div class="medium-12 columns">
    <div class="boxed" id="claimed-leads-show-box">
      <div id="claimed-leads-show-list">
        <ul id="claimed-list">
          <% @leads.each do |lead| %>
          <li><a href="/leads/<%=lead.id%>"><%=lead.company_name%></a>  <%= link_to "Unclaim Lead", {:controller => "leads", action: "unclaim", id: lead.id}, method: :post, class: "button", style: "width:165px;height:50px;" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/landing/home.html.erb
<div class=landing-bg>
  <p class="text-center" id="landing-text">
    Business Information, All in One Place.
  </p>
  <%if user_signed_in?%>
    <p class="text-center">
      <%= link_to 'Enter Site', leads_path, id: "landing-subtext1" %> ◆ <a href="https://github.com/tomfafard/lead_finder" id="landing-subtext3">Learn More</a>
    </p>
  <% else %>
    <p class="text-center">
      <%= link_to 'Browse Leads', leads_path, id: "enter-site" %> ◆ <a href="https://github.com/tomfafard/lead_finder" id="landing-subtext3">Learn More</a>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='https://fonts.googleapis.com/css?family=Fugaz+One' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:600' rel='stylesheet' type='text/css'>

    <title><%= content_for?(:title) ? yield(:title) : "LeadFinder" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1 id="title-style"><a id="home-compass" href="/"><strong>LeadFinder</strong></a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
      </ul>

      <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="has-dropdown">
          <% if user_signed_in? %>
            <li class="text-center" id="sign-out-btn"><strong><%= link_to 'Sign Out', destroy_user_session_path, class: :button, method: :delete %></strong></li>
            <li class="text-center" id="edit-info-btn"><strong><%= link_to 'Edit Info', edit_user_registration_path, class: :button %></strong></li>
          <% else %>
            <li class="text-center" id="sign-in-btn"><strong><%= link_to 'Sign In', new_user_session_path, class: :button %></strong></li>
            <li class="text-center" id="sign-up-btn"><strong><%= link_to 'Sign Up', new_user_registration_path, class: :button %></strong></li>
          <% end %>
        </li>
      </ul>
      </section>
    </nav>


    <div class="text-center" id="error-msg">
    <% flash.each do |key, value| %>
      <div data-alert class="flash">
        <%= value + " ✖︎" %>
      </div>
    <% end %>
    </div>

    <%= yield %>

  </body>
  <footer>
    <div class="text-center" id="sitemap_bg">
      <ul id="sitemap-list">
        <li><%= link_to "Landing", root_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Search Leads", leads_path %></li>
      </ul>

      <p id="copyright">copyright LOLOL</p>
    </div>
  </footer>
</html>

app/views/leads/index.html.erb
<div class="row">
  <% if user_signed_in? %>
  <div class="medium-3 columns">
  <% else %>
  <div class="medium-6 columns">
  <% end %>
    <div class="boxed" id="search-box">
      <div id="search-form">
        <h3 class="text-center" id="search-form-header">Search Leads</h3>

        <%= form_tag leads_path, method: :get do %>
        <%= label_tag :q1, "Company name" %>
        <%= text_field_tag :q1 %>
        </br>
        <%= label_tag :q2, "Address" %>
        <%= text_field_tag :q2 %>
        </br>
        <%= label_tag :q3, "City" %>
        <%= text_field_tag :q3 %>
        </br>
        <%= label_tag :q4, "State" %>
        <%= text_field_tag :q4 %>
        </br>
        <%= label_tag :q5, "Zip code" %>
        <%= text_field_tag :q5 %>
        <div class="text-center">
          <%= submit_tag "Search", class: :button %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="medium-6 columns">

    <div class="border">
      <div class="boxed" id="results-box">
        <h3 class="text-center" id="search-results-header">Search Results</h3>
        <div class="list">
          <ul id="hover-list">
            <%@leads.each do |lead|%>
              <li id="hover-list-item"><a href="/leads/<%= lead.id %>"><%= lead.company_name %></a></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="medium-3 columns">
      <div class="border">
        <div class="boxed" id="create-leads-box">
          <div id="create-leads-option">
            <h3 class="text-center" id="create-leads-header">Create Leads</h3>

            <div class="text-center">
              <%= link_to "Create a Lead →", new_lead_path, class: :button, style: "width:230px;" %>
            </div>
          </div>
        </div>

        <div class="boxed" id="claimed-leads-box">
          <div id="claimed-leads-option">
            <h3 class="text-center" id="claimed-leads-header">Claimed Leads</h3>

            <div class="text-center" id="view-claimed-header">
              <%= link_to "View Claimed Leads →", "/my_leads", class: :button, style: "width:230px;" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div><!-- row -->

app/views/leads/new.html.erb
<% if user_signed_in? %>

  <div id="new-lead-cancel">
    <%= link_to "← Cancel", leads_path %>
  </div>

  <div class="row">
    <div class="medium-5 medium-centered columns">
      <div id="new-lead-header">
        <h2 class="text-center">Create a Lead</h2>
        <hr class="text-center" id="new-lead-line-break">
      </div>

      <div class="text-center">
        <h3>General Info:</h3>
      </div>

      <%= form_for(@lead) do |f|%>
      <br>
      <%= f.label :company_name, "*Company Name" %>
      <%= f.text_field :company_name %>
      <br>
      <%= f.label :phys_address, "*Address" %>
      <%= f.text_field :phys_address %>
      <br>
      <%= f.label :phys_city, "*City" %>
      <%= f.text_field :phys_city %>
      <br>
      <%= f.label :phys_state, "*State" %>
      <%= f.select :phys_state, options_for_select(us_states, "Select") %>
      <br>
      <br>
      <%= f.label :phys_zip, "*Zip Code" %>
      <%= f.text_field :phys_zip %>
      <br>
      <%= f.label :description, "Brief Description of Company" %>
      <%= f.text_area :description, size: "5x5"%>
      <br>

      <div class="text-center">
        <h3>Contact Info:</h3>
      </div>

      <br>
      <%= f.label :phone, "Phone Number" %>
      <%= f.text_field :phone %>
      <br>
      <%= f.label :alt_phone, "Alternate Phone Number" %>
      <%= f.text_field :alt_phone %>
      <br>
      <%= f.label :toll_free_phone, "Toll-Free Phone Number" %>
      <%= f.text_field :toll_free_phone %>
      <br>
      <%= f.label :fax_phone, "Fax Number" %>
      <%= f.text_field :fax_phone %>
      <br>
      <%= f.label :website %>
      <%= f.text_field :website %>
      <br>
      <%= f.label :email, "Contact Email" %>
      <%= f.text_field :email %>
      <br>

      <div class="text-center">
        <h3>Sales Info:</h3>
      </div>

      <br>
      <%= f.label :year_est, "Year Established" %>
      <%= f.text_field :year_est %>
      <br>
      <%= f.label :area_of_dist, "Area of Distribution" %>
      <%= f.select :area_of_dist, [['Select',nil], ['Local','Local'], ['National','National'], ['International','International']] %>
      <br>
      <br>
      <%= f.label :employees_on_site, "Number of Employees on Site" %>
      <%= f.text_field :employees_on_site %>
      <br>
      <%= f.label :annual_sales, "Annual Sales" %>
      <%= f.text_field :annual_sales %>
      <br>
      <%= f.label :ownership, "Type of Ownership" %>
      <%= f.select :ownership, options_for_select(ownership, "Select") %>
      <br>
      <br>
      <%= f.label :imports, "Do they Import Goods?" %>
      <%= f.select :imports, [['Select',nil], ['Yes',true], ['No',false], ['Don\'t Know',nil]] %>
      <br>
      <%= f.label :woman_owned, "Woman Owned?" %>
      <%= f.select :woman_owned, [['Select',nil], ['Yes',true], ['No',false], ['Don\'t Know',nil]] %>
      <br>
      <%= f.label :minority_owned, "Minority Owned?" %>
      <%= f.select :minority_owned, [['Select',nil], ['Yes',true], ['No',false], ['Don\'t Know',nil]] %>
      <br>

      <div class="text-center">
        <h3>Mailing Info:</h3>
      </div>

      <br>
      <%= f.label :mail_address, "Mailing Address" %>
      <%= f.text_field :mail_address %>
      <br>
      <%= f.label :mail_city, "Mailing City" %>
      <%= f.text_field :mail_city %>
      <br>
      <%= f.label :mail_state, "Mailing State" %>
      <%= f.select :mail_state, options_for_select(us_states, "Select") %>
      <br>
      <br>
      <%= f.label :mail_zip, "Mailing Zip Code" %>
      <%= f.text_field :mail_zip %>
      <br>
      <div class="text-center">
        <%= f.submit "Create Lead", class: :button %>
        <% end %>
      </div>
    </div>
  </div>

  <div id="new-lead-cancel">
    <%= link_to "← Cancel", leads_path %>
  </div>

<% else %>

  <br>

  <div class="row">
    <div class="small-9 small-centered columns">
      <h2>You must be signed in to view this content.</h2>
      <div id="unauthed-return-home-btn">
        <%= link_to "Return Home", leads_path, class: :button %>
      </div>
    </div>
  </div>

<% end %>